<?php

use Drupal\tigre_custom\Rest\TigreRestService;

/**
 * Implements hook_preprocess_HOOK().
 */
function tigre_custom_preprocess_form_element(&$variables) {

  if ($variables['element']['#id'] == 'edit-name') {
    $variables['attributes']['class'][] = 'col-md-6';
    $variables['#title'] = t('Name');
  }

  if ($variables['element']['#id'] == 'edit-mail') {
    $variables['attributes']['class'][] = 'col-md-6';
  }

  if ($variables['element']['#id'] == 'edit-field-contato-profissao') {
    $variables['attributes']['class'][] = 'col-md-6';
  }

  if ($variables['element']['#id'] == 'edit-field-contato-empresa-0-value') {
    $variables['attributes']['class'][] = 'col-md-6';
  }


  if ($variables['element']['#id'] == 'edit-field-contato-celular-0-value') {
    $variables['attributes']['class'][] = 'col-md-6';
  }


  if ($variables['element']['#id'] == 'edit-field-contato-telefone-0-value') {
    $variables['attributes']['class'][] = 'col-md-3';
  }


  if ($variables['element']['#id'] == 'edit-field-contato-celular-0-value') {
    $variables['attributes']['class'][] = 'col-md-3';
  }

  if ($variables['element']['#id'] == 'edit-field-contato-pais') {
    $variables['attributes']['class'][] = 'col-md-6';
  }


  if ($variables['element']['#id'] == 'edit-message-0-value') {
    $variables['attributes']['class'][] = 'col-md-12';
  }


}

/**
 * Implements hook_cronapi().
 */
function tigre_custom_cronapi() {
  $items = array();
  $items['_tigre_custom_import_produto'] = array();
  return $items;
}

/*function tigre_custom_cron() {
  tigre_list_products();
}*/

function tigre_list_products_finished() {

}

function tigre_custom_queue_import_produto_cronjob() {

  /** @var QueueFactory $queue_factory */
  $queue_factory = \Drupal::service('queue');
  /** @var QueueInterface $queue */
  $queue = $queue_factory->get('import_produto_queue');

  /** @var TigreRestService $tigre_service */
  $tigre_service = new TigreRestService();
  $tigre_service->setHost("http://34.193.90.181");
  //$tigre_service->setHost("https://www.tigre.com.br");
  $tigre_service->setUsername("lucas");
  $tigre_service->setPassword('102030');
  $produtos = $tigre_service->getProducts();

  foreach ($produtos as $nid => $produto) {
    $produto_language = $produto['pt-br'];
    $detail = $tigre_service->getDetailProduct($produto_language['url']);
    $data['detail'] = $detail;
    $queue->createItem($data);
  }
}


function tigre_list_products() {
  /** @var TigreRestService $tigre_service */
  $tigre_service = new TigreRestService();
  $tigre_service->setHost("http://34.193.90.181");
  //$tigre_service->setHost("https://www.tigre.com.br");
  $tigre_service->setUsername("lucas");
  $tigre_service->setPassword('102030');
  $produtos = $tigre_service->getProducts();

  foreach ($produtos as $nid => $produto) {

    $produto_language = $produto['pt-br'];
    $detail = $tigre_service->getDetailProduct($produto_language['url']);


    //die();


  }

}